# Generated by Django 2.2 on 2019-05-15 11:07

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0002_contactperson_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactperson',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
